# Description of what this change includes
# Revision number
# Date
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create a VPC spanning 3 Availability Zones
  in us-west-2. VPC name: VPC-antpau8311.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC Configuration"
        Parameters:
          - VPCCidr

Parameters:
  VPCCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.

Mappings:
  RegionMap:
    us-west-2:
      AZs:
        - us-west-2a
        - us-west-2b
        - us-west-2c

Resources:
  # --------------------
  # VPC
  # --------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-antpau8311

  # --------------------
  # Subnets (3 AZs)
  # --------------------
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !FindInMap [RegionMap, us-west-2, AZs]]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet-A

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !FindInMap [RegionMap, us-west-2, AZs]]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet-B

  SubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [2, !FindInMap [RegionMap, us-west-2, AZs]]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet-C
  RdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
      - <SECURITY-GROUP-ID>
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: playground-db
      Engine: MySQL
      MasterUsername: Admin
      MasterUserPassword: CloudAcademy123!

Outputs:
  VPCId:
    Description: ID of the VPC
    Value: !Ref VPC

  SubnetIds:
    Description: Subnet IDs for all 3 AZs
    Value: !Join [",", [!Ref SubnetA, !Ref SubnetB, !Ref SubnetC]]
